const Router = require('express')
const router = new Router()
const achievementRouter = require('./achievementRouter')
const articleRouter = require('./articleRouter')
const exhibitionRouter = require('./exhibitionRouter')
const patentRouter = require('./patentRouter')
const grantRouter = require('./grantRouter')
const userRouter = require('./userRouter')
const subjectRouter = require('./subjectRouter')
const typeRouter = require('./typeRouter')
const universityRouter = require('./universityRouter')

router.use('/user', userRouter)
router.use('/type', typeRouter)
router.use('/subject', subjectRouter)
router.use('/university', universityRouter)
router.use('/achievement', achievementRouter)
router.use('/article', articleRouter)
router.use('/exhibition', exhibitionRouter)
router.use('/patent', patentRouter)
router.use('/grant', grantRouter)
module.exports = router
